In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [2]:
quantity = pd.read_excel("quantityReport_for_only_machine.xlsx", index_col="ID")
zone = pd.read_excel("zoneReport.xlsx", index_col="ID")
quality = pd.read_excel("qualityReport.xlsx", index_col="ID")
color = pd.read_excel("colorReport_2.xlsx", index_col="ID")

In [3]:
print(len(quantity.columns))
print(len(quality.columns))
print(len(color.columns))
print(len(zone.columns))

16
7
2
5

In [4]:
zone.isnull().sum()

Machine            0
Zone_HEAVY         0
Zone_MEDIUM        0
Zone_total         0
Zone_total_rank    0
dtype: int64

In [5]:
# pd.merge(color,zone,how="left",on=["Machine"])[pd.merge(color,zone,how="left",on=["Machine"]).isna().any(axis=1)]

In [6]:
# pd.merge(quantity,quality,how="left",on=["Machine"])[pd.merge(quantity,quality,how="left",on=["Machine"]).isna().any(axis=1)]

In [7]:
final_merging = pd.merge(pd.merge(quantity,quality,how="left",on=["Machine"]),
                         pd.merge(color,zone,how="left",on=["Machine"]),how="left",on=["Machine"])

In [8]:
final_merging[final_merging.isna().any(axis=1)]

,Machine,GrownWeight_sum,GrownWeight_less_35,Dmtr_avg,Actual_Hours_avg,GrowingHours_sum,GrownHeight_sum,GrRate_avg,GrRate_Range,GrRate_rank,...,inclusion_total,labBreakage_total,dots_total_rank,inclusion_total_rank,labBreakage_total_rank,color_counts,Zone_HEAVY,Zone_MEDIUM,Zone_total,Zone_total_rank
80,AA82,11.435000,7.432750,45.040,28.180000,28.30,0.42000,14.840000,14.5-15.0,849,...,0.000000,0.000000,23.0,5.0,4.0,"{'H': 19, 'I': 5, 'K': 1}",NaN,NaN,NaN,NaN
97,AB22,167.210265,108.686672,42.440,131.691667,468.15,6.37948,14.311667,14.0-14.5,814,...,0.263158,0.052632,889.0,848.0,24.0,"{'I': 7, 'H': 31}",NaN,NaN,NaN,NaN
208,AC53,183.150070,119.047545,42.700,142.860000,546.02,7.02672,12.802000,12.5-13.0,1,...,0.208333,0.375000,286.0,672.0,870.0,"{'H': 22, 'I': 2}",NaN,NaN,NaN,NaN
209,AC54,210.851740,137.053631,42.132,158.420000,561.65,8.00331,14.524000,14.5-15.0,832,...,0.206897,0.103448,982.0,667.0,94.0,"{'H': 22, 'I': 6, 'J': 1}",NaN,NaN,NaN,NaN
223,AC67,194.283680,126.284392,41.595,172.875000,593.32,7.47867,12.572500,12.5-13.0,1,...,0.421053,0.315789,930.0,1015.0,722.0,{'H': 19},NaN,NaN,NaN,NaN
392,AF58,160.693845,104.450999,42.545,137.625000,445.31,5.97994,12.997500,12.5-13.0,1,...,0.208333,0.375000,912.0,670.0,871.0,"{'I': 8, 'H': 13}",NaN,NaN,NaN,NaN
470,BAA12,200.274840,130.178646,41.690,162.860000,683.06,7.44940,11.050000,11.0-11.5,438,...,0.193548,0.419355,925.0,605.0,932.0,"{'H': 24, 'I': 6, 'J': 1}",NaN,NaN,NaN,NaN
528,BAB35,44.930000,29.204500,42.190,147.000000,147.00,1.70000,11.560000,11.5-12.0,287,...,0.250000,0.000000,1025.0,821.0,3.0,{'H': 4},NaN,NaN,NaN,NaN
736,BBA14,14.231205,9.250283,42.260,161.000000,36.82,0.51525,13.980000,13.5-14.0,781,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
749,BBA32,8.722080,5.669352,44.050,135.000000,21.82,0.25272,11.560000,11.5-12.0,285,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
753,BBA36,10.622240,6.904456,42.190,141.300000,27.82,0.37233,13.290000,13.0-13.5,677,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
831,BBC20,232.819515,151.332685,42.662,145.854000,680.43,7.94393,11.388000,11.0-11.5,343,...,0.161290,0.354839,869.0,488.0,829.0,"{'H': 20, 'J': 4, 'I': 5, 'K': 2}",NaN,NaN,NaN,NaN

In [9]:
if final_merging.index[0]==0:
    final_merging.index += 1

In [10]:
final_merging

,Machine,GrownWeight_sum,GrownWeight_less_35,Dmtr_avg,Actual_Hours_avg,GrowingHours_sum,GrownHeight_sum,GrRate_avg,GrRate_Range,GrRate_rank,...,inclusion_total,labBreakage_total,dots_total_rank,inclusion_total_rank,labBreakage_total_rank,color_counts,Zone_HEAVY,Zone_MEDIUM,Zone_total,Zone_total_rank
1,AA1,222.589000,144.682850,44.912500,193.450000,566.90,7.14224,12.6750,12.5-13.0,1,...,0.228571,0.485714,579.0,746.0,991.0,"{'H': 32, 'I': 3}",0.043478,0.021739,0.065217,297.0
2,AA10,191.336770,124.368900,42.023333,105.608333,542.74,6.60554,13.2450,13.0-13.5,671,...,0.237288,0.169492,626.0,766.0,257.0,"{'H': 49, 'I': 10}",0.039216,0.137255,0.176471,769.0
3,AA11,190.674980,123.938737,42.900000,126.310000,546.90,6.24838,11.9780,11.5-12.0,166,...,0.200000,0.153846,569.0,646.0,218.0,"{'H': 48, 'I': 17}",0.073529,0.044118,0.117647,525.0
4,AA12,207.805630,135.073659,40.066000,165.680000,541.40,6.46984,12.6260,12.5-13.0,1,...,0.215686,0.509804,917.0,700.0,1004.0,"{'H': 42, 'I': 9}",0.058824,0.098039,0.156863,703.0
5,AA13,220.316385,143.205650,44.770000,190.325000,568.07,6.44792,11.7000,11.5-12.0,242,...,0.204545,0.250000,940.0,656.0,545.0,"{'I': 8, 'H': 36}",0.020000,0.040000,0.060000,270.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,CC16,299.613990,194.749093,45.774000,175.700000,669.39,8.74384,12.9600,12.5-13.0,1,...,0.222222,0.203704,526.0,722.0,377.0,"{'H': 46, 'I': 8}",0.072464,0.057971,0.130435,576.0
1025,CC17,318.039400,206.725610,46.180000,164.120000,684.98,9.31195,13.5620,13.5-14.0,723,...,0.071429,0.214286,26.0,124.0,424.0,"{'H': 39, 'I': 15, 'J': 2}",0.014286,0.028571,0.042857,207.0
1026,CC20,302.204115,196.432675,45.514000,187.900000,684.48,9.00531,13.3700,13.0-13.5,690,...,0.166667,0.166667,139.0,515.0,252.0,"{'H': 32, 'I': 9, 'J': 1}",0.013889,0.013889,0.027778,147.0
1027,CC21,319.141510,207.441981,45.270000,146.160000,666.80,9.39386,14.1080,14.0-14.5,795,...,0.074074,0.148148,747.0,132.0,202.0,"{'I': 15, 'H': 38, 'J': 1}",0.045455,0.015152,0.060606,273.0
1028,CC22,213.750130,138.937585,46.242500,183.750000,480.48,6.19387,12.8675,12.5-13.0,1,...,0.250000,0.214286,729.0,817.0,419.0,"{'H': 9, 'I': 15, 'J': 4}",0.035714,0.017857,0.053571,240.0

In [11]:
final_merging.GrRate_rank = pd.to_numeric(final_merging.GrRate_rank)
final_merging.GrownWeight_sum_rank = pd.to_numeric(final_merging.GrownWeight_sum_rank)
final_merging.Actual_Hours_avg_rank = pd.to_numeric(final_merging.Actual_Hours_avg_rank)
final_merging.GrowingHours_sum_rank = pd.to_numeric(final_merging.GrowingHours_sum_rank)
final_merging.GrownHeight_sum_rank = pd.to_numeric(final_merging.GrownHeight_sum_rank)
final_merging.Dmtr_avg_rank = pd.to_numeric(final_merging.Dmtr_avg_rank)
final_merging.dots_total_rank = pd.to_numeric(final_merging.dots_total_rank)
final_merging.inclusion_total_rank = pd.to_numeric(final_merging.inclusion_total_rank)
final_merging.labBreakage_total_rank = pd.to_numeric(final_merging.labBreakage_total_rank)
final_merging.Zone_total_rank = pd.to_numeric(final_merging.Zone_total_rank)

In [12]:
final_merging['Final_total_rank'] = final_merging['GrRate_rank'] + final_merging['GrownWeight_sum_rank'] + final_merging['Actual_Hours_avg_rank'] + \
final_merging['GrowingHours_sum_rank'] + final_merging['GrownHeight_sum_rank'] + final_merging['Dmtr_avg_rank'] + final_merging['dots_total_rank'] + \
final_merging['inclusion_total_rank'] + final_merging['labBreakage_total_rank'] + final_merging['Zone_total_rank']

In [13]:
final_merging

,Machine,GrownWeight_sum,GrownWeight_less_35,Dmtr_avg,Actual_Hours_avg,GrowingHours_sum,GrownHeight_sum,GrRate_avg,GrRate_Range,GrRate_rank,...,labBreakage_total,dots_total_rank,inclusion_total_rank,labBreakage_total_rank,color_counts,Zone_HEAVY,Zone_MEDIUM,Zone_total,Zone_total_rank,Final_total_rank
1,AA1,222.589000,144.682850,44.912500,193.450000,566.90,7.14224,12.6750,12.5-13.0,1,...,0.485714,579.0,746.0,991.0,"{'H': 32, 'I': 3}",0.043478,0.021739,0.065217,297.0,4584.0
2,AA10,191.336770,124.368900,42.023333,105.608333,542.74,6.60554,13.2450,13.0-13.5,671,...,0.169492,626.0,766.0,257.0,"{'H': 49, 'I': 10}",0.039216,0.137255,0.176471,769.0,7296.0
3,AA11,190.674980,123.938737,42.900000,126.310000,546.90,6.24838,11.9780,11.5-12.0,166,...,0.153846,569.0,646.0,218.0,"{'H': 48, 'I': 17}",0.073529,0.044118,0.117647,525.0,6068.0
4,AA12,207.805630,135.073659,40.066000,165.680000,541.40,6.46984,12.6260,12.5-13.0,1,...,0.509804,917.0,700.0,1004.0,"{'H': 42, 'I': 9}",0.058824,0.098039,0.156863,703.0,7060.0
5,AA13,220.316385,143.205650,44.770000,190.325000,568.07,6.44792,11.7000,11.5-12.0,242,...,0.250000,940.0,656.0,545.0,"{'I': 8, 'H': 36}",0.020000,0.040000,0.060000,270.0,4938.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,CC16,299.613990,194.749093,45.774000,175.700000,669.39,8.74384,12.9600,12.5-13.0,1,...,0.203704,526.0,722.0,377.0,"{'H': 46, 'I': 8}",0.072464,0.057971,0.130435,576.0,2882.0
1025,CC17,318.039400,206.725610,46.180000,164.120000,684.98,9.31195,13.5620,13.5-14.0,723,...,0.214286,26.0,124.0,424.0,"{'H': 39, 'I': 15, 'J': 2}",0.014286,0.028571,0.042857,207.0,2076.0
1026,CC20,302.204115,196.432675,45.514000,187.900000,684.48,9.00531,13.3700,13.0-13.5,690,...,0.166667,139.0,515.0,252.0,"{'H': 32, 'I': 9, 'J': 1}",0.013889,0.013889,0.027778,147.0,2009.0
1027,CC21,319.141510,207.441981,45.270000,146.160000,666.80,9.39386,14.1080,14.0-14.5,795,...,0.148148,747.0,132.0,202.0,"{'I': 15, 'H': 38, 'J': 1}",0.045455,0.015152,0.060606,273.0,3262.0
1028,CC22,213.750130,138.937585,46.242500,183.750000,480.48,6.19387,12.8675,12.5-13.0,1,...,0.214286,729.0,817.0,419.0,"{'H': 9, 'I': 15, 'J': 4}",0.035714,0.017857,0.053571,240.0,4943.0

In [14]:
final_merging.columns

Index(['Machine', 'GrownWeight_sum', 'GrownWeight_less_35', 'Dmtr_avg',
       'Actual_Hours_avg', 'GrowingHours_sum', 'GrownHeight_sum', 'GrRate_avg',
       'GrRate_Range', 'GrRate_rank', 'GrownWeight_sum_rank',
       'Actual_Hours_avg_rank', 'GrowingHours_sum_rank',
       'GrownHeight_sum_rank', 'Dmtr_avg_rank', 'Total_rank', 'dots_total',
       'inclusion_total', 'labBreakage_total', 'dots_total_rank',
       'inclusion_total_rank', 'labBreakage_total_rank', 'color_counts',
       'Zone_HEAVY', 'Zone_MEDIUM', 'Zone_total', 'Zone_total_rank',
       'Final_total_rank'],
      dtype='object')

In [15]:
final_merging = final_merging.drop('Total_rank', axis=1)

In [16]:
final_merging.columns

Index(['Machine', 'GrownWeight_sum', 'GrownWeight_less_35', 'Dmtr_avg',
       'Actual_Hours_avg', 'GrowingHours_sum', 'GrownHeight_sum', 'GrRate_avg',
       'GrRate_Range', 'GrRate_rank', 'GrownWeight_sum_rank',
       'Actual_Hours_avg_rank', 'GrowingHours_sum_rank',
       'GrownHeight_sum_rank', 'Dmtr_avg_rank', 'dots_total',
       'inclusion_total', 'labBreakage_total', 'dots_total_rank',
       'inclusion_total_rank', 'labBreakage_total_rank', 'color_counts',
       'Zone_HEAVY', 'Zone_MEDIUM', 'Zone_total', 'Zone_total_rank',
       'Final_total_rank'],
      dtype='object')

In [17]:
only_ranks = final_merging[['Machine','color_counts','GrRate_Range', 'GrRate_rank','GrownWeight_sum_rank', 'GrowingHours_sum_rank','GrownHeight_sum_rank', \
                            'Actual_Hours_avg_rank', 'Dmtr_avg_rank','dots_total_rank', \
                            'inclusion_total_rank', 'labBreakage_total_rank', 'Zone_total_rank','Final_total_rank']]

In [18]:
only_ranks

,Machine,color_counts,GrRate_Range,GrRate_rank,GrownWeight_sum_rank,GrowingHours_sum_rank,GrownHeight_sum_rank,Actual_Hours_avg_rank,Dmtr_avg_rank,dots_total_rank,inclusion_total_rank,labBreakage_total_rank,Zone_total_rank,Final_total_rank
1,AA1,"{'H': 32, 'I': 3}",12.5-13.0,1,605,644,573,56,92,579.0,746.0,991.0,297.0,4584.0
2,AA10,"{'H': 49, 'I': 10}",13.0-13.5,671,876,746,788,993,804,626.0,766.0,257.0,769.0,7296.0
3,AA11,"{'H': 48, 'I': 17}",11.5-12.0,166,883,727,905,895,534,569.0,646.0,218.0,525.0,6068.0
4,AA12,"{'H': 42, 'I': 9}",12.5-13.0,1,754,752,834,433,962,917.0,700.0,1004.0,703.0,7060.0
5,AA13,"{'I': 8, 'H': 36}",11.5-12.0,242,631,634,841,73,106,940.0,656.0,545.0,270.0,4938.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1024,CC16,"{'H': 46, 'I': 8}",12.5-13.0,1,33,287,41,270,49,526.0,722.0,377.0,576.0,2882.0
1025,CC17,"{'H': 39, 'I': 15, 'J': 2}",13.5-14.0,723,21,44,20,454,33,26.0,124.0,424.0,207.0,2076.0
1026,CC20,"{'H': 32, 'I': 9, 'J': 1}",13.0-13.5,690,30,51,27,100,58,139.0,515.0,252.0,147.0,2009.0
1027,CC21,"{'I': 15, 'H': 38, 'J': 1}",14.0-14.5,795,17,324,15,694,63,747.0,132.0,202.0,273.0,3262.0
1028,CC22,"{'H': 9, 'I': 15, 'J': 4}",12.5-13.0,1,694,948,920,146,29,729.0,817.0,419.0,240.0,4943.0

In [19]:
"""[['Machine', 'GrownWeight_sum', 'GrownWeight_less_35', 'Dmtr_avg',
       'Actual_Hours_avg', 'GrowingHours_sum', 'GrownHeight_sum', 'GrRate_avg',
       'GrRate_rank', 'GrRate_Range', 'GrownWeight_sum_rank',
       'Actual_Hours_avg_rank', 'GrowingHours_sum_rank',
       'GrownHeight_sum_rank', 'Dmtr_avg_rank', 'Total_rank', 'dots_total',
       'inclusion_total', 'labBreakage_total', 'dots_total_rank',
       'inclusion_total_rank', 'labBreakage_total_rank', 'color_counts',
       'Zone_HEAVY', 'Zone_MEDIUM', 'Zone_total', 'Zone_total_rank']]"""

"[['Machine', 'GrownWeight_sum', 'GrownWeight_less_35', 'Dmtr_avg',\n       'Actual_Hours_avg', 'GrowingHours_sum', 'GrownHeight_sum', 'GrRate_avg',\n       'GrRate_rank', 'GrRate_Range', 'GrownWeight_sum_rank',\n       'Actual_Hours_avg_rank', 'GrowingHours_sum_rank',\n       'GrownHeight_sum_rank', 'Dmtr_avg_rank', 'Total_rank', 'dots_total',\n       'inclusion_total', 'labBreakage_total', 'dots_total_rank',\n       'inclusion_total_rank', 'labBreakage_total_rank', 'color_counts',\n       'Zone_HEAVY', 'Zone_MEDIUM', 'Zone_total', 'Zone_total_rank']]"

In [20]:
if os.path.exists("machine_wise_final_merging.xlsx"):
    os.remove("machine_wise_final_merging.xlsx")
    
final_merging.to_excel("machine_wise_final_merging.xlsx", header=1, index_label="ID")

In [21]:
if os.path.exists("only_Ranks.xlsx"):
    os.remove("only_Ranks.xlsx")
    
only_ranks.to_excel("only_Ranks.xlsx", header=1, index_label="ID")